accounts/urls.py
from django.contrib.auth import views as auth_views
from django.urls import reverse_lazy
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path("login/", views.login_page, name="login"),
    path("logout/", views.logout_user, name="logout"),
    path("register/", views.register_page, name="register"),
    path(
        "password_change/", auth_views.PasswordChangeView.as_view(success_url=reverse_lazy('accounts:password_change_done')),
        name="password_change"
    ),
    path(
        "password_change/done/",
        auth_views.PasswordChangeDoneView.as_view(),
        name="password_change_done",
    ),
    path("password_reset/", auth_views.PasswordResetView.as_view(), name="password_reset"),
    path(
        "password_reset/done/",
        auth_views.PasswordResetDoneView.as_view(),
        name="password_reset_done",
    ),
    path(
        "reset/<uidb64>/<token>/",
        auth_views.PasswordResetConfirmView.as_view(),
        name="password_reset_confirm",
    ),
    path(
        "reset/done/",
        auth_views.PasswordResetCompleteView.as_view(),
        name="password_reset_complete",
    ),
]

blog/urls.py
from django.urls import path, re_path
from .views import article_list, article_detail

app_name = 'blog'

urlpatterns = [
    path('', article_list, name="blog_list"),
    re_path(r'(?P<article_slug>[-\w]+)/', article_detail, name="article_detail"),
]

comments/urls.py
from django.urls import path
from .views import submit_comment, submit_reply_comment

app_name = 'comments'

urlpatterns = [
    path('submit_comment', submit_comment, name='submit_comment'),
    path('submit_reply_comment', submit_reply_comment, name='submit_reply_comment'),
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from azbankgateways.urls import az_bank_gateways_urls
from payment.views import go_to_gateway_view, callback_gateway_view
import os

if 'ADMIN_PANEL_URL' in os.environ:
    admin_panel_url = os.environ['ADMIN_PANEL_URL']
else:
    admin_panel_url = 'admin/'

urlpatterns = [
    path(admin_panel_url, admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('', include('home.urls')),
    path('courses/', include('courses.urls')),
    path('user/', include('users.urls')),
    path('blog/', include('blog.urls')),
    path('cart/', include('cart.urls')),
    path('summernote/', include('django_summernote.urls')),
    path('bankgateways/', az_bank_gateways_urls()),
    path('callback-gateway/', callback_gateway_view),
    path('go-to-gateway/', go_to_gateway_view),
    path('comment', include('comments.urls'))
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

comments/models.py
from django.conf import settings
from django.contrib.auth.models import User
from django.contrib.contenttypes.fields import GenericForeignKey
from django.contrib.contenttypes.models import ContentType
from django.db import models


class Comment(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    content = models.TextField(max_length=250)
    created_at = models.DateTimeField(auto_now_add=True)
    accepted = models.BooleanField(default=False)
    content_type = models.ForeignKey(ContentType, on_delete=models.CASCADE)
    object_id = models.PositiveIntegerField()
    content_object = GenericForeignKey()

    def __str__(self):
        return self.content

    class Meta:
        indexes = [models.Index(fields=['content_type', 'object_id'])]


class ReplyComment(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    content = models.TextField(max_length=250)
    created_at = models.DateTimeField(auto_now_add=True)
    accepted = models.BooleanField(default=False)
    comment = models.ForeignKey(Comment, on_delete=models.CASCADE, related_name='replies')

    def __str__(self):
        return self.content

comments/forms.py
from django import forms
from .models import Comment, ReplyComment


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['content']


class ReplyCommentForm(forms.ModelForm):
    class Meta:
        model = ReplyComment
        fields = ['content']

comments/views.py
from django.contrib import messages
from django.contrib.contenttypes.models import ContentType
from .models import Comment, ReplyComment
from django.shortcuts import redirect, get_object_or_404
from urllib.parse import unquote
from courses.models import Course
from blog.models import Article


def submit_comment(request):
    referer = request.META.get('HTTP_REFERER')
    slug = unquote(referer.split('/')[4])

    if '/courses/' in referer:
        app_label = 'courses'
        model = 'course'
        object_id = get_object_or_404(Course, slug=slug).id
    elif '/articles/' in referer:
        app_label = 'blog'
        model = 'article'
        object_id = get_object_or_404(Article, slug=slug).id
    else:
        app_label = model = object_id = None

    data = dict(**request.POST)
    user_id = request.user.id
    content = data['content'][0]

    if len(content) > 250:
        messages.success(request, 'متن شما نباید بیشتر از 250 کاراکتر باشد')
        return redirect(request.META.get('HTTP_REFERER'))

    content_type_id = get_object_or_404(ContentType, app_label=app_label, model=model).id
    comment = Comment(user_id=user_id, content=content, content_type_id=content_type_id, object_id=object_id)
    comment.save()

    messages.success(request, 'نظر شما ارسال شد و پس از بررسی منتشر می شود')
    return redirect(request.META.get('HTTP_REFERER'))


def submit_reply_comment(request):
    data = dict(**request.POST)
    user_id = request.user.id
    content = data['content'][0]

    if len(content) > 250:
        messages.success(request, 'متن شما نباید بیشتر از 250 کاراکتر باشد')
        return redirect(request.META.get('HTTP_REFERER'))

    comment_id = data['comment'][0]
    reply = ReplyComment(user_id=user_id, content=content, comment_id=comment_id)
    reply.save()

    messages.success(request, 'نظر شما ارسال شد و پس از بررسی منتشر می شود')
    return redirect(request.META.get('HTTP_REFERER'))

comments/templates/comments/comments-section.html
{% load static %}
{% load jalali_tags %}
{% load comment_extras %}
{% load custom_tags %}

<link rel="stylesheet" href="{% static 'comments/css/comments-section.css' %}">

<div class="comment-section">
    <h2>نظرات</h2>
    {% if messages %}
    <ul class="messages">
        {% for message in messages %}
            <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
        {% endfor %}
    </ul>
    {% endif %}

    {% for comment in comments %}
        <div class="comment">
        <div class="avatar">
            {% if comment.user.avatar %}
                <img src="{{ comment.user.avatar.url }}" alt="User Avatar">
            {% else %}
                <img src="{% static 'img/user-avatar.png' %}" alt="User Avatar">
            {% endif %}
        </div>
        <div class="comment-content">
            {% if comment.user.get_full_name %}
                <p class="username">{{ comment.user.get_full_name }}</p>
            {% else %}
                <p class="username">{{ comment.user }}</p>
            {% endif %}
            <p class="text">{{ comment.content }}</p>
            <p class="comment-datetime">{{ comment.created_at|to_jalali:'%Y/%m/%d - %H:%M:%S'|to_persian }} &nbsp;| &nbsp;</p>

            {% if user.is_authenticated %}
                <button class="reply-button">پاسخ</button>
            {% endif %}

            <form method="post" action="{% url 'comments:submit_reply_comment' %}">
                {% csrf_token %}
                <div class="reply-section">
                    <textarea id="content" name="content" rows="4" required style="margin-right: -5px;" class="text-input"></textarea>
                    <button class="submit-reply">ارسال</button>
                    <input type="hidden" name="comment" value="{{ comment.id }}"/>
                </div>
            </form>
            {% for reply in comment.replies.all|is_accepted %}
                <div class="comment">
                <div class="avatar">
                    {% if reply.user.avatar %}
                        <img src="{{ reply.user.avatar.url }}" alt="User Avatar">
                    {% else %}
                        <img src="{% static 'img/user-avatar.png' %}" alt="User Avatar">
                    {% endif %}
                </div>
                <div class="comment-content">
                    {% if reply.user.get_full_name %}
                        <p class="username">{{ reply.user.get_full_name }}</p>
                    {% else %}
                        <p class="username">{{ reply.user }}</p>
                    {% endif %}
                    <p class="text">{{ reply.content }}</p>
                    <p class="comment-datetime">{{ reply.created_at|to_jalali:'%Y/%m/%d - %H:%M:%S'|to_persian }}</p>
                </div>
                </div>
            {% endfor %}
        </div>
        </div>
    {% empty %}
        <br><h5 align="center">اولین نفری باشید که نظری می نویسد !</h5>
    {% endfor %}

    <br>
    <div class="comment-form">
    {% if user.is_authenticated %}
        <h2>نظر خود را ثبت کنید</h2>
        <form method="post" action="{% url 'comments:submit_comment' %}">
            {% csrf_token %}
            <div class="input-field">
                <label for="content">نظر شما</label>
                <textarea id="content" name="content" rows="4" required style="margin-right: -5px;"></textarea>
            </div>
            <button type="submit">ارسال</button>
        </form>
    {% else %}
        <a href="{% url 'accounts:login' %}">برای نظر دادن لطفا وارد حساب کاربری خود شوید</a>
    {% endif %}
    </div>

</div>

<script src="{% static 'comments/js/comments-section.js' %}"></script>