accounts/urls.py
from django.contrib.auth import views as auth_views
from django.urls import reverse_lazy
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path("login/", views.login_page, name="login"),
    path("logout/", views.logout_user, name="logout"),
    path("register/", views.register_page, name="register"),
    path(
        "password_change/", auth_views.PasswordChangeView.as_view(success_url=reverse_lazy('accounts:password_change_done')),
        name="password_change"
    ),
    path(
        "password_change/done/",
        auth_views.PasswordChangeDoneView.as_view(),
        name="password_change_done",
    ),
    path("password_reset/", auth_views.PasswordResetView.as_view(), name="password_reset"),
    path(
        "password_reset/done/",
        auth_views.PasswordResetDoneView.as_view(),
        name="password_reset_done",
    ),
    path(
        "reset/<uidb64>/<token>/",
        auth_views.PasswordResetConfirmView.as_view(),
        name="password_reset_confirm",
    ),
    path(
        "reset/done/",
        auth_views.PasswordResetCompleteView.as_view(),
        name="password_reset_complete",
    ),
]

blog/urls.py
from django.urls import path, re_path
from .views import article_list, article_detail

app_name = 'blog'

urlpatterns = [
    path('', article_list, name="blog_list"),
    re_path(r'(?P<article_slug>[-\w]+)/', article_detail, name="article_detail"),
]

cart/urls.py
from django.urls import path, re_path
from .views import add_to_cart, cart, pay, delete_course_from_cart

app_name = 'cart'

urlpatterns = [
    path("", cart, name="cart"),
    path("pay", pay, name="pay"),
    path("add-to-cart/<int:course_id>", add_to_cart, name="add_to_cart"),
    path("delete-course-from-cart/", delete_course_from_cart, name="delete_course_from_cart"),
]

courses/urls.py
from django.urls import path, re_path
from .views import courses_list, course_detail, register_free_course, search_courses

app_name = 'courses'

urlpatterns = [
    path('', courses_list, name="courses_list"),
    path('register/<int:course_id>', register_free_course, name='register_free_course'),
    re_path(r'^search(?P<keyword>\w{0,50})/$', search_courses, name='search_courses'),
    re_path(r'(?P<course_slug>[-\w]+)/', course_detail, name="course_detail"),
]

home/urls.py
from django.urls import path
from .views import home_page, about_page, contact_page

app_name = 'home'

urlpatterns = [
    path('', home_page, name="home_page"),
    path('about', about_page, name="about_page"),
    path('contact', contact_page, name="contact_page"),
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from azbankgateways.urls import az_bank_gateways_urls
from payment.views import go_to_gateway_view, callback_gateway_view
import os

if 'ADMIN_PANEL_URL' in os.environ:
    admin_panel_url = os.environ['ADMIN_PANEL_URL']
else:
    admin_panel_url = 'admin/'

urlpatterns = [
    path(admin_panel_url, admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('', include('home.urls')),
    path('courses/', include('courses.urls')),
    path('user/', include('users.urls')),
    path('blog/', include('blog.urls')),
    path('cart/', include('cart.urls')),
    path('summernote/', include('django_summernote.urls')),
    path('bankgateways/', az_bank_gateways_urls()),
    path('callback-gateway/', callback_gateway_view),
    path('go-to-gateway/', go_to_gateway_view),
    path('comment', include('comments.urls'))
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from .views import user_profile, user_courses

app_name = 'users'

urlpatterns = [
    path('profile', user_profile, name="user_profile"),
    path('courses', user_courses, name="user_courses"),
]

home/views.py
from django.shortcuts import render
from django.db.models import Count
from courses.models import Course


def home_page(request):
    courses = Course.objects.annotate(count=Count('users')).filter(is_published=True).order_by('-count')[:3]
    return render(request, 'home/index.html', {'courses': courses})


def about_page(request):
    return render(request, 'home/about.html')


def contact_page(request):
    return render(request, 'home/contact.html')

home/templates/home/about.html
{% extends 'home/base.html' %}

{% block title %}درباره کافه کد{% endblock title %}

{% block content %}
<div class="container" style="margin: 60px; width: 80%; margin-right: 10%;">
  <p class="text-center" style="font-size: 50px">درباره کافه کد</p>
  <div class="text-center" style="margin: 50px;">
  <p>
      کافه کد در مهر ماه سال 1402 راه اندازی شد تا با ارائه آموزش های خوب برای برنامه نویسان عزیز کشور، کمک کوچکی برای رشد اونها در این زمینه بکنه.
  </p>
  </div>
</div>
{% endblock content %}

home/templates/home/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en" dir="rtl">

<head>
    <meta charset="utf-8">
    <title>{% block title %}{% endblock title%}</title>
    {% include 'home/base_ref.html' %}
</head>

<body>
    {% include 'home/header.html' %}

    {% block content %}{%  endblock content %}

    {% include 'home/footer.html' %}

    <!-- JavaScript Libraries -->
    <script src="{% static 'js/jquery-3.4.1.min.js' %}"></script>
    <script src="{% static 'css/bootstrap.bundle.min.js' %}"></script>
    <script src="{% static 'js/wow.min.js' %}"></script>
    <script src="{% static 'js/easing.min.js' %}"></script>
    <script src="{% static 'js/waypoints.min.js' %}"></script>
    <script src="{% static 'js/owl.carousel.min.js' %}"></script>

    <!-- Template Javascript -->
    <script src="{% static 'js/main.js' %}"></script>
</body>

home/templates/home/base_ref.html
{% load static %}

    <meta content="width=device-width, initial-scale=1.0" name="viewport">
    <meta content="" name="keywords">
    <meta content="" name="description">

    <!-- Favicon -->
    <link href="{% static 'img/favicon.ico' %}" rel="icon">

    <!-- Google Web Fonts -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <!-- <link href="https://fonts.googleapis.com/css2?family=Heebo:wght@400;500;600&family=Nunito:wght@600;700;800&display=swap" rel="stylesheet"> -->

    <!-- Icon Font Stylesheet -->
    <link href="{% static 'css/all.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/icons/bootstrap-icons.css' %}" rel="stylesheet">

    <!-- Libraries Stylesheet -->
    <link href="{% static 'css/animate.min.css' %}" rel="stylesheet">
    <link href="{% static 'js/assets/owl.carousel.min.css' %}" rel="stylesheet">

    <!-- Customized Bootstrap Stylesheet -->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Template Stylesheet -->
    <link href="{% static 'css/style.css' %}" rel="stylesheet">

home/templates/home/contact.html
{% extends 'home/base.html' %}

{% block title %}تماس با ما{% endblock title %}

{% block content %}
<div class="container" style="margin: 60px; width: 80%; margin-right: 10%;">
  <p class="text-center" style="font-size: 50px">تماس با ما</p>
  <div class="text-center" style="margin: 50px;">
  <p>
      آدرس: قزوین ... خیابان ...</br></br>
      شماره تماس: 09338785474 </br></br>
      ایمیل: alihv5000@gmail.com
  </p>
  </div>
</div>
{% endblock content %}

home/templates/home/footer.html
{% load static %}

<!-- Footer Start -->
<div class="container-fluid bg-dark text-light footer pt-5 mt-5 wow fadeIn" data-wow-delay="0.1s">
    <div class="container py-5">
        <div class="row g-5">
            <div class="col-lg-3 col-md-6">
                <h4 class="text-white mb-3">لینک های سریع</h4>
                <a class="btn-link" href="">درباره ما</a></br>
                <a class="btn-link" href="">تماس با ما</a></br>
                <a class="btn-link" href="">قوانین سایت</a></br>
                <a class="btn-link" href="">شرایط استفاده</a></br>
                <a class="btn-link" href="">راهنما</a>
            </div>
            <div class="col-lg-3 col-md-6">
                <h4 class="text-white mb-3">راه های ارتباطی</h4>
                <p class="mb-2"><i class="fa fa-map-marker-alt me-3"></i> قزوین، خیابان ...، کوچه ...</p>
                <p class="mb-2"><i class="fa fa-phone-alt me-3"></i> 5474 878 933 98+</p>
                <p class="mb-2"><i class="fa fa-envelope me-3"></i> alihv5000@gmail.com</p>
                <div class="d-flex pt-2">
                    <a class="btn btn-outline-light btn-social" href=""><i class="fab fa-twitter"></i></a>
                    <a class="btn btn-outline-light btn-social" href=""><i class="fab fa-facebook-f"></i></a>
                    <a class="btn btn-outline-light btn-social" href=""><i class="fab fa-youtube"></i></a>
                    <a class="btn btn-outline-light btn-social" href=""><i class="fab fa-linkedin-in"></i></a>
                </div>
            </div>
            <div class="col-lg-3 col-md-6">
                <h4 class="text-white mb-3">اخبار</h4>
                <p>برای اطلاع از آخرین اخبار و تخفیف ها، ایمیل خود را وارد کنید</p>
                <div class="position-relative mx-auto" style="max-width: 400px;">
                    <input class="form-control border-0 w-100 py-3 ps-4 pe-5" type="text" placeholder="ایمیل شما">
                    <button type="button" class="btn btn-primary py-2 bp3-position-left top-0 end-0 mt-2 me-2">مشترک شدن</button>
                </div>
            </div>
            <div class="col-lg-3 col-md-6">
{#                <div style="float: left">#}
                    <a referrerpolicy='origin' target='_blank' href='https://trustseal.enamad.ir/?id=409801&Code=Iye2fYqU3qLDSCw9KbHjzKW2V5rvo1ww'><img referrerpolicy='origin' src='https://trustseal.enamad.ir/logo.aspx?id=409801&Code=Iye2fYqU3qLDSCw9KbHjzKW2V5rvo1ww' alt='' style='cursor:pointer' Code='Iye2fYqU3qLDSCw9KbHjzKW2V5rvo1ww'></a>
{#                </div>#}

                <div style="float: left">
                    <script src="https://static.idpay.ir/trust.js?id=01HDDXDDPW94TYM480E9E6S5FK&width=64"></script>
                </div>
            </div>
        </div>
    </div>
    <div class="container">
        <div class="copyright">
            <div class="row">
                <div class="col-md-6 text-center text-md-start mb-3 mb-md-0">
                    &copy; <a class="border-bottom" href="#">CodCafe</a>, All Right Reserved.

                    <!--/*** This template is free as long as you keep the footer author’s credit link/attribution link/backlink. If you'd like to use the template without the footer author’s credit link/attribution link/backlink, you can purchase the Credit Removal License from "https://htmlcodex.com/credit-removal". Thank you for your support. ***/-->
                    Designed By <a class="border-bottom" href="https://htmlcodex.com">HTML Codex</a>
                </div>
                <div class="col-md-6 text-center text-md-end">
                    <div class="footer-menu">
                        <a href="{% url 'home:home_page' %}">خانه</a>
                        <a href="{% url 'blog:blog_list' %}">بلاگ</a>
                        <a href="{% url 'courses:courses_list' %}">دوره ها</a>
                        <a href="{% url 'home:about_page' %}">درباره ما</a>
                        <a href="{% url 'home:contact_page' %}">تماس با ما</a>
                        <a></a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- Footer End -->


<!-- Back to Top -->
<a href="#" class="btn btn-lg btn-primary btn-lg-square back-to-top"><i class="bi bi-arrow-up"></i></a>

home/templates/home/header.html
{% load static %}

<!-- Spinner Start
<div id="spinner" class="show bg-white position-fixed translate-middle w-100 vh-100 top-50 start-50 d-flex align-items-center justify-content-center">
    <div class="spinner-border text-primary" style="width: 3rem; height: 3rem;" role="status">
        <span class="sr-only">در حال بارگذاری ...</span>
    </div>
</div>
 Spinner End -->


<!-- Navbar Start -->
<nav class="navbar navbar-expand-lg bg-white navbar-light shadow sticky-top p-0">
  <a href="{% url 'home:home_page' %}">
    <img src="{% static 'img/logo.png' %}" alt="site logo" class="navbar-brand">
  </a>
  <a href="{% url 'home:home_page' %}">
    <p class="navbar-nav ms-auto p-4 p-lg-0 nav-item" style="color: saddlebrown; font-size: 25px;">&nbsp;کافه کد</p>
  </a>
    <button type="button" class="navbar-toggler me-4" data-bs-toggle="collapse" data-bs-target="#navbarCollapse">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarCollapse">
        <div class="navbar-nav ms-auto p-4 p-lg-0">
            <a href="{% url 'home:home_page' %}" class="nav-item nav-link">خانه</a>
            <a href="{% url 'courses:courses_list' %}" class="nav-item nav-link">دوره ها</a>
            <a href="{% url 'blog:blog_list' %}" class="nav-item nav-link">بلاگ</a>
            <a href="{% url 'home:about_page' %}" class="nav-item nav-link">درباره ما</a>
            <a href="{% url 'home:contact_page' %}" class="nav-item nav-link">تماس با ما</a>
        </div>

        <!-- Search Box Start -->
        <form class="input-group rounded" action="{% url 'courses:search_courses' keyword=q %}" method="get">
          <input type="search" name="q" class="form-control" id="search-input" placeholder="جستجو" aria-label="Search" aria-describedby="search-addon"/>
          <button type="submit" class="input-group-text border-0" id="search-addon">
            <i class="fas fa-search"></i>
          </button>
        </form>
        <!-- Search Box End -->


        <div class="button-group">
            {% if user.is_authenticated %}
              <div class="dropdown">
                {% if user.avatar %}
                    <button class="dropbtn" style="background-image: url({{ user.avatar.url }});"></button>
                {% else %}
                    <button class="dropbtn" style="background-image: url({% static 'img/user-avatar.png' %});"></button>
                {% endif %}
                <div class="dropdown-content">
                  <a href="{% url 'users:user_profile' %}"><i class="bi bi-person" style="margin-left: 8px"></i>پروفایل</a>
                  <a href="{% url 'users:user_courses' %}"><i class="bi bi-folder2" style="margin-left: 8px"></i>دوره های من</a>
                  <a href="{% url 'cart:cart' %}" style="margin-right: -8px;">
                      <span class='badge badge-warning' id='lblCartCount'> {{ user.user_cart.courses.count }} </span>
                      <i class="bi bi-cart" style="margin-left: 8px"></i>
                      سبد خرید</a>
                  <a href="{% url 'accounts:logout' %}" class="logout"><i class="bi bi-door-open" style="margin-left: 8px"></i>خروج</a>
                </div>
              </div>
            {% else %}
              <a href="{% url 'accounts:login' %}"><button class="button login-button">ورود</button></a>
              <a href="{% url 'accounts:register' %}"><button class="button register-button">ثبت نام</button></a>
            {% endif %}
        </div>
    </div>
</nav>
<!-- Navbar End -->

home/templates/home/index.html
{% extends 'home/base.html' %}
{% load static %}

{% block title %}کافه کد - لذت یادگیری{% endblock %}

{% block content %}
    <!-- Carousel Start -->
    <div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
        <div class="carousel-inner">
          <div class="carousel-item active">
           <img class="d-block w-100" src="{% static 'img/home.jpg' %}" alt="First slide">
          </div>
        </div>
      </div>
    <!-- Carousel End -->


    <!-- Service Start -->
    <div class="container-xxl py-5">
        <div class="container">
            <div class="row g-4">
                <div class="col-lg-3 col-sm-6 wow fadeInUp" data-wow-delay="0.1s">
                    <div class="service-item text-center pt-3" style="border-radius: 30px">
                        <div class="p-4">
                            <i class="fa fa-3x fa-graduation-cap text-primary mb-4"></i>
                            <h5 class="mb-3">آموزش های اصولی</h5>
                            <p>آموزش های اصولی و هدایت دانشجو به مسیر مناسب</p>
                        </div>
                    </div>
                </div>
                <div class="col-lg-3 col-sm-6 wow fadeInUp" data-wow-delay="0.3s">
                    <div class="service-item text-center pt-3" style="border-radius: 30px">
                        <div class="p-4">
                            <i class="fa fa-3x fa-globe text-primary mb-4"></i>
                            <h5 class="mb-3">کلاس های آنلاین</h5>
                            <p>کلاس های آنلاین با اساتید کاربلد و امکان پرسش و پاسخ با اساتید</p>
                        </div>
                    </div>
                </div>
                <div class="col-lg-3 col-sm-6 wow fadeInUp" data-wow-delay="0.5s">
                    <div class="service-item text-center pt-3" style="border-radius: 30px">
                        <div class="p-4">
                            <i class="fa fa-3x fa-home text-primary mb-4"></i>
                            <h5 class="mb-3">پروژه محور</h5>
                            <p>دوره های پروژه محور و انجام پروژه ها واقعی در تمامی دوره ها</p>
                        </div>
                    </div>
                </div>
                <div class="col-lg-3 col-sm-6 wow fadeInUp" data-wow-delay="0.7s">
                    <div class="service-item text-center pt-3" style="border-radius: 30px">
                        <div class="p-4">
                            <i class="fa fa-3x fa-book-open text-primary mb-4"></i>
                            <h5 class="mb-3">آپدیت های ماهانه</h5>
                            <p>آپدیت های ماهانه دوره ها و بروز شدن دوره ها توسط اساتید</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- Service End -->


    <!-- About Start -->
    <div class="container-xxl py-5">
        <div class="container">
            <div class="row g-5">
                <div class="col-lg-6 wow fadeInUp" data-wow-delay="0.1s" style="min-height: 400px;">
                    <div class="position-relative h-100">
                        <img class="img-fluid position-absolute w-100 h-100" src="{% static 'img/home-small.jpg' %}" alt="" style="object-fit: cover; border-radius: 30px">
                    </div>
                </div>
                <div class="col-lg-6 wow fadeInUp" data-wow-delay="0.3s">
                    <h6 class="section-title bg-white text-start text-primary pe-3">درباره ما</h6>
                    <h1 class="mb-4">به کافه کد خوش آمدید!</h1>
                    <p class="mb-4">ما اینجا در کافه کد به دنبال ارتقای سطح برنامه نویسان خوب کشورمون هستیم</p>
                    <p class="mb-4">دوره های کافه کد توسط اساتید کاربلد و بالاترین کیفیت تهیه میشن و از این بابت هیچ نگرانی نداشته باشید</p>
                    <div class="row gy-2 gx-4 mb-4">
                        <div class="col-sm-6">
                            <p class="mb-0">اساتید کاربلد</p>
                        </div>
                        <div class="col-sm-6">
                            <p class="mb-0">کیفیت بالا</p>
                        </div>
                        <div class="col-sm-6">
                            <p class="mb-0">آپدیت های ماهانه</p>
                        </div>
                        <div class="col-sm-6">
                            <p class="mb-0">پروژه محور</p>
                        </div>
                        <div class="col-sm-6">
                            <p class="mb-0">کلاس های آنلاین</p>
                        </div>
                        <div class="col-sm-6">
                            <p class="mb-0">مدرک معتبر</p>
                        </div>
                    </div>
                    <a class="btn btn-primary py-3 px-5 mt-2" href="{% url "home:about_page" %}" style="border-radius: 30px">بیشتر بخوانید</a>
                </div>
            </div>
        </div>
    </div>
    <!-- About End -->

    <!-- Courses Start -->
    <div class="container-xxl py-5">
        <div class="container">
            <div class="text-center wow fadeInUp" data-wow-delay="0.1s">
                <h6 class="section-title bg-white text-center text-primary px-3">دوره ها</h6>
                <h1 class="mb-5">محبوب ترین دوره ها</h1>
            </div>
            {% include 'courses/course_card.html' with courses=courses %}
        </div>
    </div>
    <!-- Courses End -->
{% endblock content %}