accounts/urls.py
from django.contrib.auth import views as auth_views
from django.urls import reverse_lazy
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path("login/", views.login_page, name="login"),
    path("logout/", views.logout_user, name="logout"),
    path("register/", views.register_page, name="register"),
    path(
        "password_change/", auth_views.PasswordChangeView.as_view(success_url=reverse_lazy('accounts:password_change_done')),
        name="password_change"
    ),
    path(
        "password_change/done/",
        auth_views.PasswordChangeDoneView.as_view(),
        name="password_change_done",
    ),
    path("password_reset/", auth_views.PasswordResetView.as_view(), name="password_reset"),
    path(
        "password_reset/done/",
        auth_views.PasswordResetDoneView.as_view(),
        name="password_reset_done",
    ),
    path(
        "reset/<uidb64>/<token>/",
        auth_views.PasswordResetConfirmView.as_view(),
        name="password_reset_confirm",
    ),
    path(
        "reset/done/",
        auth_views.PasswordResetCompleteView.as_view(),
        name="password_reset_complete",
    ),
]

blog/urls.py
from django.urls import path, re_path
from .views import article_list, article_detail

app_name = 'blog'

urlpatterns = [
    path('', article_list, name="blog_list"),
    re_path(r'(?P<article_slug>[-\w]+)/', article_detail, name="article_detail"),
]

home/urls.py
from django.urls import path
from .views import home_page, about_page, contact_page

app_name = 'home'

urlpatterns = [
    path('', home_page, name="home_page"),
    path('about', about_page, name="about_page"),
    path('contact', contact_page, name="contact_page"),
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from azbankgateways.urls import az_bank_gateways_urls
from payment.views import go_to_gateway_view, callback_gateway_view
import os

if 'ADMIN_PANEL_URL' in os.environ:
    admin_panel_url = os.environ['ADMIN_PANEL_URL']
else:
    admin_panel_url = 'admin/'

urlpatterns = [
    path(admin_panel_url, admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('', include('home.urls')),
    path('courses/', include('courses.urls')),
    path('user/', include('users.urls')),
    path('blog/', include('blog.urls')),
    path('cart/', include('cart.urls')),
    path('summernote/', include('django_summernote.urls')),
    path('bankgateways/', az_bank_gateways_urls()),
    path('callback-gateway/', callback_gateway_view),
    path('go-to-gateway/', go_to_gateway_view),
    path('comment', include('comments.urls'))
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from .views import user_profile, user_courses

app_name = 'users'

urlpatterns = [
    path('profile', user_profile, name="user_profile"),
    path('courses', user_courses, name="user_courses"),
]

users/views.py
from django.shortcuts import render
from courses.models import Course


def user_profile(request):
    return render(request, 'users/dashboard.html')


def user_courses(request):
    courses = Course.objects.filter(users=request.user)
    context = {'courses': courses}
    return render(request, 'users/courses.html', context=context)

users/templates/users/courses.html
{% block content %}
    {% include 'courses/index.html' with courses=courses %}
{% endblock content %}

users/templates/users/dashboard.html
{% load static %}

<link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">

<style>
    body{
        margin-top:20px;
        color: #1a202c;
        text-align: left;
        background-color: #e2e8f0;    
    }
    .main-body {
        padding: 15px;
    }
    .card {
        box-shadow: 0 1px 3px 0 rgba(0,0,0,.1), 0 1px 2px 0 rgba(0,0,0,.06);
    }
    
    .card {
        position: relative;
        display: flex;
        flex-direction: column;
        min-width: 0;
        word-wrap: break-word;
        background-color: #fff;
        background-clip: border-box;
        border: 0 solid rgba(0,0,0,.125);
        border-radius: .25rem;
    }
    
    .card-body {
        flex: 1 1 auto;
        min-height: 1px;
        padding: 1rem;
    }
    
    .gutters-sm {
        margin-right: -8px;
        margin-left: -8px;
    }
    
    .gutters-sm>.col, .gutters-sm>[class*=col-] {
        padding-right: 8px;
        padding-left: 8px;
    }
    .mb-3, .my-3 {
        margin-bottom: 1rem!important;
    }
    
    .bg-gray-300 {
        background-color: #e2e8f0;
    }
    .h-100 {
        height: 100%!important;
    }
    .shadow-none {
        box-shadow: none!important;
    }
</style>

<div class="container" dir="rtl">
    <div class="main-body">
    
          <!-- Breadcrumb -->
          <nav aria-label="breadcrumb" class="main-breadcrumb">
            <ol class="breadcrumb">
              <li class="breadcrumb-item"><a href="{% url "home:home_page" %}">خانه&nbsp/</a></li>
              <li class="breadcrumb-item"><a href="javascript:void(0)">&nbsp&nbspکاربر</a></li>
              <li class="breadcrumb-item active" aria-current="page">پروفایل</li>
            </ol>
          </nav>
          <!-- /Breadcrumb -->
    
          <div class="row gutters-sm">
            <div class="col-md-4 mb-3">
              <div class="card">
                <div class="card-body">
                  <div class="d-flex flex-column align-items-center text-center">
                    <img src="{% static 'img/user-avatar.png' %}" alt="user-avatar" class="rounded-circle" width="150">
                    <div class="mt-3">
                      <h4>{{ user.username}}</h4>
                      <a href="{% url 'users:user_courses' %}"><button class="btn btn-outline-primary" style="border-radius: 20px;">
                          دوره های من
                      </button></a>
                    </div>
                  </div>
                </div>
              </div>
            </div>
            <div class="col-md-8">
              <div class="card mb-3">
                <div class="card-body">
                  <div class="row">
                    <div class="col-sm-3">
                      <h6 class="mb-0">نام</h6>
                    </div>
                    <div class="col-sm-9 text-secondary">
                      {{ user.first_name }}
                    </div>
                  </div>
                  <hr>
                  <div class="row">
                    <div class="col-sm-3">
                      <h6 class="mb-0">نام خانوادگی</h6>
                    </div>
                    <div class="col-sm-9 text-secondary">
                      {{ user.last_name }}
                    </div>
                  </div>
                  <hr>
                  <div class="row">
                    <div class="col-sm-3">
                      <h6 class="mb-0">ایمیل</h6>
                    </div>
                    <div class="col-sm-9 text-secondary">
                      {{ user.email }}
                    </div>
                  </div>
                  <hr>
                  <div class="row">
                    <div class="col-sm-3">
                      <h6 class="mb-0">رمز عبور</h6>
                    </div>
                    <div class="col-sm-9 text-secondary">
                      ********
                    </div>
                  </div>
                  <hr>
                  <div class="row">
                    <div class="col-sm-12">
                      <a class="btn btn-info " style="border-radius: 20px; color: white" target="__blank" href="{% url 'accounts:password_change' %}">تغییر رمز عبور</a>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
    </div>