blog/urls.py
from django.urls import path, re_path
from .views import article_list, article_detail

app_name = 'blog'

urlpatterns = [
    path('', article_list, name="blog_list"),
    re_path(r'(?P<article_slug>[-\w]+)/', article_detail, name="article_detail"),
]

cart/urls.py
from django.urls import path, re_path
from .views import add_to_cart, cart, pay, delete_course_from_cart

app_name = 'cart'

urlpatterns = [
    path("", cart, name="cart"),
    path("pay", pay, name="pay"),
    path("add-to-cart/<int:course_id>", add_to_cart, name="add_to_cart"),
    path("delete-course-from-cart/", delete_course_from_cart, name="delete_course_from_cart"),
]

courses/urls.py
from django.urls import path, re_path
from .views import courses_list, course_detail, register_free_course, search_courses

app_name = 'courses'

urlpatterns = [
    path('', courses_list, name="courses_list"),
    path('register/<int:course_id>', register_free_course, name='register_free_course'),
    re_path(r'^search(?P<keyword>\w{0,50})/$', search_courses, name='search_courses'),
    re_path(r'(?P<course_slug>[-\w]+)/', course_detail, name="course_detail"),
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from azbankgateways.urls import az_bank_gateways_urls
from payment.views import go_to_gateway_view, callback_gateway_view
import os

if 'ADMIN_PANEL_URL' in os.environ:
    admin_panel_url = os.environ['ADMIN_PANEL_URL']
else:
    admin_panel_url = 'admin/'

urlpatterns = [
    path(admin_panel_url, admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('', include('home.urls')),
    path('courses/', include('courses.urls')),
    path('user/', include('users.urls')),
    path('blog/', include('blog.urls')),
    path('cart/', include('cart.urls')),
    path('summernote/', include('django_summernote.urls')),
    path('bankgateways/', az_bank_gateways_urls()),
    path('callback-gateway/', callback_gateway_view),
    path('go-to-gateway/', go_to_gateway_view),
    path('comment', include('comments.urls'))
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

courses/models.py
from django.conf import settings
from django.contrib.contenttypes.fields import GenericRelation
from django.db import models
from mysite.models import TimeStampedModel
from django.contrib.auth.models import User
from django.core.validators import MaxValueValidator
from comments.models import Comment


class Teacher(models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    bio = models.TextField(verbose_name="Teacher Bio")

    def __str__(self):
        return self.user.username

    def get_full_name(self):
        return f'{self.user.first_name} {self.user.last_name}'


class Category(models.Model):
    name = models.CharField(max_length=20, verbose_name='Category Name')

    def __str__(self):
        return self.name

    class Meta:
        verbose_name_plural = 'Categories'


class Chapter(models.Model):
    title = models.CharField(max_length=100)
    course = models.ForeignKey("Course", on_delete=models.CASCADE)

    def __str__(self):
        return self.title


class Video(models.Model):
    title = models.CharField(max_length=250, blank=False, verbose_name='Video Title')
    video = models.FileField(upload_to='videos/courses/%Y-%m-%d/', verbose_name='Video File')  # TODO add file validator
    uploaded_date = models.DateTimeField(auto_now=True)
    sequence_number = models.PositiveIntegerField()
    duration = models.PositiveIntegerField()
    chapter = models.ForeignKey(Chapter, on_delete=models.CASCADE, default=None)
    course = models.ForeignKey("Course", on_delete=models.CASCADE, related_name="video_course") # Just for easier managing

    def __str__(self):
        return self.title


class Course(TimeStampedModel):
    STATUS_CHOICES = (('going', 'Going On'), ('done', 'Done'))

    title = models.CharField(max_length=250, blank=False)
    slug = models.SlugField(unique=True, max_length=255, allow_unicode=True)
    detail = models.TextField()
    image = models.ImageField(upload_to='photos/courses/%Y-%m-%d/')
    price = models.PositiveIntegerField(default=0)
    discount = models.PositiveIntegerField(validators=[MaxValueValidator(100)], default=0)
    status = models.CharField(max_length=8, default='Going On', choices=STATUS_CHOICES)
    is_published = models.BooleanField(default=False)
    category = models.ForeignKey(Category, on_delete=models.CASCADE, related_name='category')
    teacher = models.ForeignKey(Teacher, on_delete=models.CASCADE, related_name='teacher')
    videos = models.ManyToManyField(Video, blank=True, related_name="course_videos")
    users = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='enrolled_courses', blank=True)
    comments = GenericRelation(Comment)

    def __str__(self):
        return self.title

    def get_final_price(self):
        return int(self.price * (100 - self.discount) / 100)

courses/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth.decorators import login_required

from cart.models import UserCart, TemporaryOrder
from .models import Course


def courses_list(request):
    courses = Course.objects.filter(is_published=True)
    context = {'courses': courses}

    return render(request, 'courses/index.html', context=context)


def course_detail(request, course_slug):
    course = get_object_or_404(Course, slug=course_slug)
    course_duration = sum(video.duration for video in course.videos.all())
    course_duration = int(course_duration / 60)
    comments = course.comments.filter(accepted=True)

    context = {'course': course, 'comments': comments, 'duration': course_duration, }

    return render(request, 'courses/course.html', context=context)


def register_free_course(request, course_id):
    if request.user.is_authenticated:
        course_user_field = get_object_or_404(Course, id=course_id)
        course_user_field.users.add(request.user)
        return redirect('courses:course_detail', course_slug=course_user_field.slug)
    else:
        return redirect('accounts:login')


def search_courses(request, keyword):
    keyword = request.GET.get('q')
    courses = Course.objects.filter(title__contains=keyword, is_published=True)
    context = {'courses': courses}

    return render(request, 'courses/index.html', context=context)


def register_items(request, tracking_code):
    user_order = get_object_or_404(TemporaryOrder, tracking_code=tracking_code)
    temp_courses = user_order.courses.all()

    for course in temp_courses:
        course.users.add(request.user)
        course.save()

    user_order.delete()

    user_cart = get_object_or_404(UserCart, user=request.user)

    for course in user_cart.courses.all():
        if course in temp_courses:
            user_cart.courses.remove(course)

    user_cart.save()


def delete_failed_temporary_order(tracking_code):
    user_order = get_object_or_404(TemporaryOrder, tracking_code=tracking_code)
    user_order.delete()

courses/templates/courses/course.html
{% extends 'home/base.html' %}
{% load jalali_tags %}
{% load humanize %}
{% load static %}
{% load custom_tags %}

{% block title %}{{ course.title }}{% endblock title %}

{% block content %}
<div class="container mt-5">
    <!-- Course Title -->
    <h1 class="title text-center" style="margin: 80px; font-size: 50px">{{ course.title }}</h1>
    <div class="row">
        <div class="col-lg-8 mb-4">
            <!-- Course Image -->
            <img src="{{ course.image.url }}" alt="Course Image" class="img-fluid rounded">
        </div>

        <div class="col-lg-4">
            <div class="course-details">
                <div>
                    <span><i class="fa fa-money-bill-wave course-details-icon"></i>قیمت</span>
                    <span>
                        <!-- Course Price -->
                        {% if course.price == 0 %}
                            <span class="course-details-price">رایگان</span>
                        {% else %}
                            <span class="course-details-price">{{ course.get_final_price|intcomma }} تومان </span>
                        {% endif %}
                    </span>
                </div>

                <div>
                    <span><i class="fa fa-clock course-details-icon"></i>طول دوره</span>
                    <span>
                        <!-- Course Duration -->
                        <span class="course-details-info">{{ duration }} ساعت</span>
                    </span>
                </div>


                <div>
                    <span><i class="fa fa-clock course-details-icon"></i>تاریخ شروع دوره</span>
                    <span>
                        <!-- Course Duration -->
                        <span class="course-details-info">
                            {{ course.created_date|to_jalali:'%Y/%m/%d'|to_persian }}
                        </span>
                    </span>
                </div>

                <div>
                    <span><i class="fa fa-clock course-details-icon"></i>آخرین آپدیت دوره</span>
                    <span>
                        <!-- Course Duration -->
                        <span class="course-details-info">
                            {{ course.updated_date|to_jalali:'%Y/%m/%d'|to_persian }}
                        </span>
                    </span>
                </div>

                <div>
                    <span><i class="fa fa-clock course-details-icon"></i>مدرس دوره</span>
                    <span>
                        <!-- Course Duration -->
                        <span class="course-details-info">{{ course.teacher.get_full_name }}</span>
                    </span>
                </div>

                <div>
                    <span><i class="fa fa-clock course-details-icon"></i>وضعیت دوره</span>
                    <span>
                        <!-- Course Duration -->
                        {% if course.status == 'going' %}
                            <span class="course-details-info">درحال برگزاری</span>
                        {% else %}
                            <span class="course-details-info">به اتمام رسیده</span>
                        {% endif %}
                    </span>
                </div>
                <hr>

                <!-- Register Course Button -->
                {% if user in course.users.all %}
                    <button class="btn btn-primary btn-lg btn-block" style="width: 100%">شما به این دوره دسترسی دارید</button>
                {% elif course in user.user_cart.courses.all %}
                    <a class="btn btn-primary btn-lg btn-block" style="width: 100%">به سبد خرید اضافه شده است</a>
                {% elif course.price != 0 %}
                    <a href="{% url 'cart:add_to_cart' course.id %}" class="btn btn-primary btn-lg btn-block" style="width: 100%">افزودن به سبد خرید</a>
                {% else %}
                    <a href="{% url 'courses:register_free_course' course.id %}" class="btn btn-primary btn-lg btn-block" style="width: 100%">ثبت نام</a>
                {% endif %}
            </div>
        </div>
    </div>

    <!-- Additional Course Details -->
    <div class="row mt-5">
        <div class="col-md-12" style="width: 95%; margin-right: 10px;">
            <h2>توضیحات دوره</h2>
            <p>{{ course.detail|safe }}</p>
        </div>
    </div>

    <!-- Course Videos List -->
    <div class="row mt-5">
        <div class="col-md-12">
            <h2 style="margin-right: 3%;">ویدئو ها</h2></br>
            <div class="course-list" style="float: right; width: 100%;">
                {% for chapter in course.chapter_set.all %}
                    <div class="chapter">
                        <div class="chapter-header">
                            <h2 class="chapter-title">{{ chapter.title }}</h2>
                            <span class="dropdown-toggle"></span>
                        </div>
                        <ul class="chapter-dropdown">
                            {% for video in chapter.video_set.all %}
                                <li>
                                    {% if access %}
                                        <a href="{{ video.video.url }}" style="color: #0dcaf0">{{ video.title }}</a>
                                        <a href="{{ video.video.url }}" style="margin: 10px;">
                                            <i class="bi bi-download" style="float: left;"></i>
                                        </a>
                                    {% else %}
                                        <a>{{ video.title }}</a>
                                        <i class="fa fa-lock" style="float: left;"></i>
                                    {% endif %}
                                </li>
                            {% endfor %}
                        </ul>
                    </div>
                {% endfor %}
            </div>
            <script src="{% static 'js/video-list.js' %}"></script>
        </div>
    </div><br><br><br><br>

    <!-- start comment section -->
    {% include 'comments/comments-section.html' with comments=comments course=course %}
    <!-- end comment section -->

</div>

{% endblock content %}

courses/templates/courses/course_card.html
{% load humanize %}

<div class="row g-4 justify-content-center" style="margin-top: 30px; width: 95%; margin-right: 10px;">
    {% for course in courses %}
        <div class="col-lg-4 col-md-6 wow fadeInUp" data-wow-delay="0.1s">
            <div class="course-item bg-light" style="border-radius: 30px">
                <div class="position-relative overflow-hidden">
                    <a href="{% url 'courses:course_detail' course_slug=course.slug %}"><img class="img-fluid" src="{{ course.image.url }}" alt="" style="border-radius: 30px 30px 0 0"></a>
                    <div class="w-100 d-flex justify-content-center position-absolute bottom-0 start-0 mb-4">
                        <a href="{% url 'courses:course_detail' course_slug=course.slug %}" class="flex-shrink-0 btn btn-sm btn-primary px-3 border-end" style="border-radius:30px;">اطلاعات بیشتر</a>
                    </div>
                </div>
                <div class="text-center p-4 pb-0">
                    <a href="{% url 'courses:course_detail' course_slug=course.slug %}"><h3 class="mb-0">{{ course.title }}</h3></a>
                    {% comment %}
                    <div class="mb-3">
                        <small class="fa fa-star text-primary"></small>
                        <small class="fa fa-star text-primary"></small>
                        <small class="fa fa-star text-primary"></small>
                        <small class="fa fa-star text-primary"></small>
                        <small class="fa fa-star text-primary"></small>
                        <small>(123)</small>
                    </div>
                    {% endcomment %}
                    </br>
                    {% if course.price == 0 %}
                    <h5 class="course-card-price mb-4">رایگان</h5>
                    {% else %}
                    <h5 class="course-card-price mb-4" style="color: white">{{ course.get_final_price|intcomma }} تومان </h5>
                    {% endif %}
                </div>
                <div class="d-flex border-top">
                    <small class="flex-fill text-center border-end py-2"><i class="fa fa-user-tie text-primary me-2"></i>
                        {{ course.teacher.get_full_name }}</small>
                    <small class="flex-fill text-center py-2"><i class="fa fa-user text-primary me-2"></i>
                        {{ course.users.all|length }}</small>
                </div>
            </div>
        </div>
    {% empty %}
        <p class="text-center" style="font-size: 50px;">دوره ای یافت نشد!</p>
    {% endfor %}
</div>

courses/templates/courses/index.html
{% extends 'home/base.html' %}
{% load static %}

{% block title %}کافه کد - دوره ها{% endblock title %}

{% block content %}
    {% include 'courses/course_card.html' with courses=courses %}
{% endblock content %}